### ISSUE TITLE
Crash on connected

### ISSUE THREAD

**Issue by piroor** [benpye/wsl-ssh-pageant#7] opened 2017-08-04 16:26 UTC
On my environment, it crashes when I try to connect to the Pageant. Until I actually connect the process is running, but it suddenly dies by any connection. Here is a log:

```
$ while true; do socat UNIX-LISTEN:/tmp/wsl-ssh-pageant.socket,unlink-close,unlink-early TCP4:127.0.0.1:13000; done &
$ export SSH_AUTH_SOCK=/tmp/wsl-ssh-pageant.socket
$ /mnt/c/Program\ Files/wsl-ssh-pageant/wsl-ssh-pageant.exe  &
[2] 6085
$ Listening on 127.0.0.1:13000
$ git pull
Unhandled Exception: System.IO.FileNotFoundException
   at System.Net.SocketAddressPal.GetAddressFamily(Byte[] buffer)
   at System.Net.Sockets.IPEndPointExtensions.Create(EndPoint thisObj, SocketAddress socketAddress)
   at System.Net.Sockets.AcceptOverlappedAsyncResult.PostCompletion(Int32 numBytes)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

 * Bash: Bash on Ubuntu on Windows (Ubuntu 16.04), on Windows 10 Creators Update
 * Pageant: Pageant 0.7.0 (bundled to TortoiseGit)

**Comment by benpye** [comment] 2017-11-29 16:04
Hm, I don't see this behaviour here. Do you see this on the Fall Creators Update?

**Comment by benpye** [comment] 2017-12-29 15:18
Closing this as I can't reproduce. @piroor If you managed to get this issue to occur again please let me know.

**Closed as completed by benpye** 2017-12-29 15:18 UTC
