### ISSUE TITLE
Connection always refused

### ISSUE THREAD

**Issue by shokinn** [benpye/wsl-ssh-pageant#45] opened 2020-12-22 15:45 UTC
Hey there,
I'm currently facing the issue no matter what I do, I always get an Connection refused by the ssh-agend inside of my WSL 2 instance.

Here what I did:
- Downloaded and put the wsl-ssh-pageant-amd64.exe to C:\Tools\wsl-ssh-agent\wsl-ssh-pageant-amd64.exe.
- Create the directory `C:\wsl-ssh-pageant`
- Run pagent
- Loaded the public key to pagent (the key is stored in my KeePass file, KeePassXC loads the key into the pagent)
- Started wsl-ssh-pageant-amd64.exe within cmd (`C:\Tools\wsl-ssh-agent\wsl-ssh-pageant-amd64.exe --systray --wsl C:\wsl-ssh-pageant\ssh-agent.sock --verbose`)
- set `SSH_AUTH_SOCK` to `SSH_AUTH_SOCK`
- Ran `ssh-add -l`

Output inside of WSL:  
```
[phg@AINCRAD ~]$ export SSH_AUTH_SOCK=/mnt/c/wsl-ssh-pageant/ssh-agent.sock
[phg@AINCRAD ~]$ ssh-add -l
Error connecting to agent: Connection refused
```

Output from wsl-ssh-pageant-amd64 running on windows:
```
C:\Users\philip>C:\Tools\wsl-ssh-agent\wsl-ssh-pageant-amd64.exe --systray --wsl C:\wsl-ssh-pageant\ssh-agent.sock --verbose
2020/12/22 15:47:05 Listening on Unix socket: C:\wsl-ssh-pageant\ssh-agent.sock
```

The strange thing is that I don't get any log messages that there was a try to connect to socket.

I also tried to put the socket file in different locations.
No change of this behaviour.

Any Ideas where i'm doing mistakes?

**Comment by benpye** [comment] 2020-12-30 05:15
Just to check, is this WSL 1 or WSL 2?

**Comment by shokinn** [comment] 2020-12-30 14:32
WSL 2.
![grafik](https://user-images.githubusercontent.com/10045300/103358295-94becb80-4ab5-11eb-89fa-218d1d8eff38.png)

**Comment by eneiford** [comment] 2021-01-03 01:42
I am experiencing the exact same behavior.  Any update / resolution?

**Comment by kohenkatz** [comment] 2021-01-06 23:27
Looks like a duplicate of #33

**Comment by benpye** [comment] 2022-08-06 18:03
Thanks @kohenkatz - it does look like this is a duplicate of #33 . Unfortunately WSL 2 doesn't have any `AF_UNIX` type socket support, so using the named pipe with npiperelay is probably the best solution.

**Closed as completed by benpye** 2022-08-06 18:03 UTC
